/* O OPERADOR NOT '!' TEM COMO O ATRIBUTO DE 
INVERTER VALORES BOLEANOS EM NUMEROS
STRINGS VALORES NULOS VALORES INDEFINIDOS
ENTRE OUTROS....   */
//console.log ((2+2) === 4)

console.log (!(2+2) === 4)
